### PR TITLE
Improve code readability

### PR DESCRIPTION
**Pull request by Prayag2**
This PR does a few things to improve code readability so that's it's easier to develop and contribute to the application.

### Changes
- Split the code into three files, `funcs.py`, `consts.py`, and `app.py`.
- Created two functions `ask_gpt` and `type_message` to reduce repeated lines of code.
- Added docstrings to every function so that future contributors can understand the code more easily.
- Refactored the code according to PyLint's suggestions to follow best practices (pylint score is above 9.5).
- Formatted the code using [black](https://github.com/psf/black) formatter for Python to improve code consistency.
- Added a `.gitignore` file to ignore pycache and venv.
- It will now use the OS environment variables to get the API keys. Users can provide their API keys in the `.env` file.

### CODE REVIEW

**Comment by Prayag2** [comment]
Pls don't forget to add `hacktoberfest-accepted` label XD

**Comment by Prayag2** [comment]
I've fixed the recursion problem.

**Comment by programmingninjas** [comment]
Great work @Prayag2  👍

**Comment by Prayag2** [comment]
Bery noice :smiley_cat: 
Thank you for merging!!

**Pull request merged**
